---
abstract: 'Add a plugin pipeline to your cows'
author:
  - 'Jon Portnoy <avenj@cobaltirc.org>'
build_requires:
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300030, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MooX-Role-Pluggable
requires:
  Carp: 0
  Moo: 1.000007
  Scalar::Util: 0
  Try::Tiny: 0
  namespace::clean: 0.23
  perl: v5.10.1
  strictures: 1
resources:
  repository: git://github.com/avenj/moox-role-pluggable.git
version: 0.120001
